const apps = [
  { name: "23andMe", tags: ["Misc"] },
  { name: "Airbnb", tags: ["Misc"] },
  { name: "Amazon", tags: ["Misc"] },
  { name: "Ancestry", tags: ["Misc"] },
  { name: "Apple Health", tags: ["Health"] },
  { name: "Bosch", tags: ["Health"] },
  { name: "Doordash", tags: ["Misc"] },
  { name: "Evernote", tags: ["Misc"] },
  { name: "Facebook", tags: ["Social"] },
  { name: "Fitbit", tags: ["Health"] },
  { name: "Google Calendar", tags: ["Misc"] },
  { name: "Google Maps", tags: ["Transport"] },
  { name: "Google", tags: ["Misc"] },
  { name: "Instacart", tags: ["Misc"] },
  { name: "Instagram", tags: ["Social"] },
  { name: "iTunes", tags: ["Social"] },
  { name: "Linkedin", tags: ["Social"] },
  { name: "Lyft", tags: ["Transport"] },
  { name: "Maps", tags: ["Transport"] },
  { name: "Medium", tags: ["Social"] },
  { name: "Netflix", tags: ["Social"] },
  { name: "Notion", tags: ["Misc"] },
  { name: "Oura", tags: ["Health"] },
  { name: "Peloton", tags: ["Health"] },
  { name: "Polar", tags: ["Health"] },
  { name: "Prime Video", tags: ["Social"] },
  { name: "Reddit", tags: ["Social"] },
  { name: "Runkeeper", tags: ["Health"] },
  { name: "Snapchat", tags: ["Social"] },
  { name: "Spotify", tags: ["Social"] },
  { name: "Strava", tags: ["Health"] },
  { name: "Suunto", tags: ["Health"] },
  { name: "Tiktok", tags: ["Social"] },
  { name: "Tripadvisor", tags: ["Misc"] },
  { name: "Twitch", tags: ["Social"] },
  { name: "Twitter", tags: ["Social"] },
  { name: "Uber Eats", tags: ["Misc"] },
  { name: "Uber", tags: ["Transport"] },
  { name: "Waze", tags: ["Transport"] },
  { name: "Withings", tags: ["Health"] },
  { name: "Youtube", tags: ["Social"] },
];

const avatars = [
  "Avatar1.svg",
  "Avatar2.svg",
  "Avatar3.svg",
  "Avatar4.svg",
  "Avatar5.svg",
  "Avatar6.svg",
  "Avatar7.svg",
  "Avatar8.svg",
  "Avatar9.svg",
  "Avatar10.svg",
  "Avatar11.svg",
  "Avatar12.svg",
];

export { apps, avatars };
